Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install --yes python-software-properties
    sudo add-apt-repository ppa:nginx/stable
    sudo apt-get update
    sudo apt-get install --yes nginx
    # scp -F ssh.config ./nginx.conf vagrant@default:~/
    # vagrant ssh nginx
    # sudo mv ./nginx.conf /etc/nginx/conf.d/default.conf
    #   server 127.0.0.1:7000 -> 192.168.33.31:4000
    #   server 127.0.0.1:7001 -> 192.168.33.31:4001
    # sudo service nginx restart
  SHELL
end
