Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo DEBIAN_FRONTEND=noninteractive apt-get install --yes mysql-server
    mycnf="/etc/mysql/my.cnf"
    if [ -f "${mycnf}" ]; then
      sed -i.bak -e "s/^bind-address/#bind-address/g" ${mycnf}
    fi

    mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION; FLUSH PRIVILEGES;"
    sudo service mysql restart
  SHELL
end
