Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 6379, host: 6379
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install --yes redis-server
    redisconf="/etc/redis/redis.conf"
    if [ -f "${redisconf}" ]; then
      sed -i.bak -e "s/^bind 127.0.0.1/bind 0.0.0.0/g" ${redisconf}
    fi
    sudo /etc/init.d/redis-server restart
  SHELL
end
